name: Build Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Run security scans
      - name: Security scan
        run: |
          pip install bandit
          bandit -r .

      # Build the Docker image
      - name: Build image
        run: |
          docker build -t sgrsaga/django_sample:latest .

      # Log in to the Docker registry
      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push the image to the Docker registry
      - name: Push image
        run: |
          docker push sgrsaga/django_sample:latest
